## Config file
lr:                     1e-4 # Initial learning rate

# TODO: Fix
# epochs:                 100 # Number of epochs to train the model 
epochs:                 100 # Number of epochs to train the model 
number_classes:         1 # Number of classes in the target dataset
batch_size_tr:          2 # Batch size for train
batch_size_va:          1 # Batch size for validation 
saved_model:            './checkpoints/weights_deepcrack.model'
saved_model_final:      './checkpoints/weights_deepcrack_final.model'

# TODO: Add
# path_to_tradata:        './DeepCrack/train' #path to dataset (./Crack500/train)
# path_to_valdata:        './DeepCrack/test'  #path to dataset (./Crack500/test)
# path_to_testdata:       './DeepCrack/test'  #path to dataset (./Crack500/val)

# path_to_tradata:        './data/palm/palm-all-fixed-w300-h380-negative/train' #path to dataset 
# path_to_valdata:        './data/palm/palm-all-fixed-w300-h380-negative/test'  #path to dataset 
# path_to_testdata:       './data/palm/palm-all-fixed-w300-h380-negative/test'  #path to dataset

path_to_tradata:        './data/palm-manual/PalmAll_Manual_Thick3_300_400/train' 
path_to_valdata:        './data/palm-manual/PalmAll_Manual_Thick3_300_400/test'  
path_to_testdata:       './data/palm-manual/PalmAll_Manual_Thick3_300_400/test'  

# path_to_testdata:   './data/palm/etc'

patience:               6 # number of epochs without improvement to do before finishing training early.reduce the lr
progress_p:             0.5 # value between 0-1 shows the number of time we need to report training progress in each epoch
pretrained:             0 # load the previously trained weight or no value should either 1 or 0
loss_filename:         'loss_log.txt'
save_result:           './results/' # path to save results
# save_result:           './results/manual-predict-' # path to save results.

# Add
saved_model_log:       './checkpoints/log/all-fixed-w300-h380-negative-e50/weights_deepcrack.model'
path_to_inference_data:  './data/palm/etc/'

results_path:          './results/all-manual-same-400-e100'